# Generated by Django 5.1.4 on 2025-01-29 02:58

import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(validators=[laboratorio.models.validar_fecha_fabricacion]),
        ),
    ]
